
version: '3'
services:
  mariadb:
    image: bitnami/mariadb:11.4
    ports:
      - "3306"
    environment:
      - MARIADB_USER=user_moodle
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=db_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  moodle:
    image: bitnami/moodle:4.4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=user_moodle
      - MOODLE_DATABASE_NAME=db_moodle
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      - MOODLE_DATABASE_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MOODLE_SITE_NAME=${SITE_NAME}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
